import { randomUUID } from 'node:crypto';
import { DomainError } from './domain-error';
import type { SessionClaims, SessionCredentials } from './session-input';
export type MembershipState = 'member' | 'not-member' | 'unknown';
export interface ValidatedSession { email: string; accountId: string; }
export interface JoinAttempt { membership: MembershipState; requestAccepted: boolean; inviteAccepted: boolean; }
export interface JoinClient { validateSession(credentials: SessionCredentials, claims: SessionClaims): Promise<ValidatedSession>; requestJoin(credentials: SessionCredentials, workspaceId: string): Promise<JoinAttempt>; verifyMembership(credentials: SessionCredentials, workspaceId: string): Promise<MembershipState>; }
export type FetchLike = (input: string | URL, init?: RequestInit) => Promise<Response>;
export interface JoinClientOptions { baseUrl: string; timeoutMs: number; maxRetries: number; retryBackoffMs: number; }
const json = async (response: Response): Promise<unknown> => { try { return await response.json() as unknown; } catch { return null; } };
const contains = (value: unknown, needle: string): boolean => JSON.stringify(value)?.toLowerCase().includes(needle.toLowerCase()) ?? false;
export class ChatGptJoinClient implements JoinClient {
  constructor(private readonly options: JoinClientOptions, private readonly fetchImpl: FetchLike = fetch, private readonly sleep: (ms: number) => Promise<void> = (ms) => new Promise((resolve) => setTimeout(resolve, ms)), private readonly uuid: () => string = randomUUID) {}
  async validateSession(credentials: SessionCredentials, claims: SessionClaims): Promise<ValidatedSession> { const response = await this.call('GET', '/backend-api/me', credentials); if (!response.ok) throw new DomainError(response.status >= 500 ? 'UPSTREAM_TIMEOUT' : 'SESSION_INVALID', 'Không thể xác minh session.'); const body = await json(response); const email = this.findString(body, ['email'])?.toLowerCase(); const accountId = this.findString(body, ['chatgpt_account_id', 'account_id', 'id']); if (!email || !accountId || email !== claims.email || accountId !== claims.accountId) throw new DomainError('SESSION_INVALID', 'Session không hợp lệ.'); return { email, accountId }; }
  async requestJoin(credentials: SessionCredentials, workspaceId: string): Promise<JoinAttempt> { const request = await this.call('POST', `/backend-api/accounts/${workspaceId}/invites/request`, credentials); const requestAccepted = request.ok || request.status === 409; const accept = await this.call('POST', `/backend-api/accounts/${workspaceId}/invites/accept`, credentials); const inviteAccepted = accept.ok || accept.status === 409; const membership = await this.verifyMembership(credentials, workspaceId); if (!requestAccepted && !inviteAccepted && membership !== 'member') throw new DomainError('JOIN_REJECTED', 'Lời mời không được chấp nhận.'); return { membership, requestAccepted, inviteAccepted }; }
  async verifyMembership(credentials: SessionCredentials, workspaceId: string): Promise<MembershipState> { for (const endpoint of ['/backend-api/accounts/check/v4-2023-04-27', '/backend-api/me']) { const response = await this.call('GET', endpoint, credentials); if (!response.ok) continue; const body = await json(response); if (contains(body, workspaceId)) return 'member'; } return 'not-member'; }
  private findString(value: unknown, keys: string[]): string | undefined { if (!value || typeof value !== 'object') return undefined; const obj = value as Record<string, unknown>; for (const key of keys) if (typeof obj[key] === 'string') return obj[key]; for (const child of Object.values(obj)) { const result = this.findString(child, keys); if (result) return result; } return undefined; }
  private async call(method: string, path: string, credentials: SessionCredentials): Promise<Response> { let lastStatus = 0; for (let attempt = 1; attempt <= Math.max(1, this.options.maxRetries); attempt++) { try { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.options.timeoutMs); try { const response = await this.fetchImpl(`${this.options.baseUrl}${path}`, { method, signal: controller.signal, headers: { accept: '*/*', authorization: `Bearer ${credentials.accessToken}`, 'content-type': 'application/json', 'oai-device-id': this.uuid(), 'oai-language': 'en-US' } }); clearTimeout(timer); lastStatus = response.status; if (response.status === 429 || response.status >= 500) { if (attempt < this.options.maxRetries) { await this.sleep(this.options.retryBackoffMs); continue; } } return response; } finally { clearTimeout(timer); } } catch (error) { if (attempt >= this.options.maxRetries) throw new DomainError('UPSTREAM_TIMEOUT', 'ChatGPT tạm thời không phản hồi.', `attempt:${attempt}`); await this.sleep(this.options.retryBackoffMs); } } throw new DomainError('UPSTREAM_TIMEOUT', 'ChatGPT tạm thời không phản hồi.', `status:${lastStatus}`); }
}
