create extension if not exists pgcrypto;
create table public.app_settings (id smallint primary key default 1 check (id = 1), invite_workspace_id uuid, updated_at timestamptz not null default now());
insert into public.app_settings (id, invite_workspace_id) values (1, null) on conflict (id) do nothing;
create table public.cdks (id uuid primary key default gen_random_uuid(), code_hash text not null unique check (code_hash ~ '^[0-9a-f]{64}$'), status text not null default 'unused' check (status in ('unused', 'used')), email text, used_at timestamptz, result text check (result in ('processing','accepted','already_member','join_rejected','accept_not_found','worker_unavailable','upstream_timeout','internal_error','service_interrupted')), workspace_id uuid, created_at timestamptz not null default now(), check ((status = 'unused' and email is null and used_at is null and result is null and workspace_id is null) or (status = 'used' and email is not null and used_at is not null and result is not null and workspace_id is not null)));
create index cdks_created_at_idx on public.cdks (created_at desc); create index cdks_status_created_at_idx on public.cdks (status, created_at desc);
create or replace function public.enforce_cdk_one_way() returns trigger language plpgsql set search_path = '' as $$ begin
  if new.code_hash is distinct from old.code_hash then raise exception 'CDK_HASH_IMMUTABLE'; end if;
  if old.status = 'used' and new.status <> 'used' then raise exception 'CDK_CANNOT_RETURN_UNUSED'; end if;
  if old.status = 'used' and (new.email is distinct from old.email or new.used_at is distinct from old.used_at or new.workspace_id is distinct from old.workspace_id) then raise exception 'CDK_USAGE_SNAPSHOT_IMMUTABLE'; end if;
  if old.result is distinct from new.result and old.result is not null and old.result <> 'processing' then raise exception 'CDK_RESULT_FINAL'; end if; return new; end; $$;
create trigger cdks_enforce_one_way before update on public.cdks for each row execute function public.enforce_cdk_one_way();
create or replace function public.consume_cdk(p_code_hash text, p_email text, p_workspace_id uuid) returns table (id uuid, email text, workspace_id uuid, used_at timestamptz, result text) language sql security invoker set search_path = '' as $$ update public.cdks set status = 'used', email = lower(btrim(p_email)), used_at = now(), result = 'processing', workspace_id = p_workspace_id where code_hash = p_code_hash and status = 'unused' and nullif(btrim(p_email), '') is not null and p_workspace_id is not null returning cdks.id,cdks.email,cdks.workspace_id,cdks.used_at,cdks.result; $$;
alter table public.app_settings enable row level security; alter table public.cdks enable row level security;
revoke all on table public.app_settings from public, anon, authenticated; revoke all on table public.cdks from public, anon, authenticated; revoke all on table public.app_settings from service_role; revoke all on table public.cdks from service_role; revoke all on function public.enforce_cdk_one_way() from public, anon, authenticated; revoke all on function public.consume_cdk(text,text,uuid) from public, anon, authenticated, service_role;
grant select on table public.app_settings to service_role; grant update (invite_workspace_id,updated_at) on table public.app_settings to service_role; grant select,insert on table public.cdks to service_role; grant update (status,email,used_at,result,workspace_id) on table public.cdks to service_role; grant execute on function public.enforce_cdk_one_way() to service_role; grant execute on function public.consume_cdk(text,text,uuid) to service_role;
